"use client";
import { useMemo, useState } from "react";
import { ArrowDown, ArrowUpRight, ChevronRight, Linkedin, Plus, X } from "lucide-react";
import { LoadingScreen } from "@/components/loading-screen";
import { Navigation } from "@/components/navigation";
import { Cursor } from "@/components/cursor";
import { Motion } from "@/components/motion";
import { ecosystem, stats } from "@/data/site";
import { initiatives } from "@/data/initiatives";
import { events } from "@/data/events";
import { team } from "@/data/team";
import { archive } from "@/data/archive";

const ledger = [["2026", "EDC Summit launched", "A new annual room for the region's most restless builders."], ["2025", "Incubation program introduced", "A focused path from experiment to first venture."], ["2025", "1,000 students reached", "A milestone built through open doors and ambitious questions."], ["2024", "Ecosystem established", "A small group formed the beginning of a much larger idea."]];
export default function Home() { const [node, setNode] = useState(0); const [filter, setFilter] = useState("ALL"); const [person, setPerson] = useState<typeof team[number] | null>(null); const filtered = useMemo(() => archive.filter(a => filter === "ALL" || a.year === filter || a.category.toUpperCase() === filter), [filter]); return <main><LoadingScreen/><Cursor/><Motion/><Navigation/>
  <section className="hero" id="home"><div className="hero-kicker">01 — ENTREPRENEUR DEVELOPMENT CELL <span>EST. 2024</span></div><div className="hero-art"><div/><i/><b/></div><div className="hero-statement"><p>TURN</p><p>IDEAS</p><p>INTO <em>IMPACT.</em></p></div><aside className="hero-note"><strong>EDC</strong><span>ENTREPRENEURSHIP<br/>INNOVATION<br/>LEADERSHIP</span></aside><a className="scroll" href="#about">SCROLL TO EXPLORE <ArrowDown size={14}/></a><div className="hero-foot">13°04&apos;N / 80°16&apos;E <span>IDEAS NEED ROOM.</span></div></section>
  <section className="about section" id="about"><span className="section-number">01</span><div className="about-title reveal">WE DON&apos;T<br/>JUST TALK<br/>ABOUT<br/><em>ENTREPRENEURSHIP.</em></div><div className="about-copy reveal"><span className="line"/> <p>We&apos;re a student-led engine for the people willing to see the world differently—and do something about it.</p><h3>WE BUILD<br/><i>AROUND IT.</i></h3><a href="#initiatives">OUR APPROACH <ArrowUpRight size={16}/></a></div></section>
  <section className="ecosystem section"><header><span>02 — ECOSYSTEM</span><h2>THE EDC<br/><em>ECOSYSTEM</em></h2></header><div className="system"><div className="system-list">{ecosystem.map((e,i) => <button className={node===i?"active":""} onMouseEnter={()=>setNode(i)} onFocus={()=>setNode(i)} onClick={()=>setNode(i)} key={e.id}><b>0{i+1}</b>{e.name}<ChevronRight size={16}/></button>)}</div><div className="system-view"><span>ACTIVE MODULE / 0{node+1}</span><div className="orb"><i/><i/><i/><b>EDC</b></div><h3>{ecosystem[node].name}</h3><p>{ecosystem[node].copy}</p></div></div></section>
  <section className="initiatives section" id="initiatives"><header><span>03 — INITIATIVES</span><h2>WHAT WE<br/><em>BUILD</em></h2><p>Multiple ways in. One shared intention: make progress matter.</p></header><div className="initiative-grid">{initiatives.map((x,i)=><article className={`initiative ${x.shape} reveal`} key={x.id}><span>{x.tag}</span><h3>{x.title.split("\n").map((line, lineIndex) => <span className="initiative-line" key={`${x.id}-${lineIndex}`}>{line}{lineIndex < x.title.split("\n").length - 1 && <br/>}</span>)}</h3><p>{x.copy}</p><ArrowUpRight/><div className="card-wire">0{i+1}</div></article>)}</div></section>
  <section className="impact"><span>04 — THE NUMBERS</span><div>{stats.map(s=><article key={s.id} className="reveal"><strong>{s.value}</strong><p>{s.label}</p></article>)}</div></section>
  <section className="events section" id="events"><header><span>05 — EVENTS</span><h2>EVENTS<br/>THAT <em>MOVE</em><br/>PEOPLE.</h2><p>DRAG OR SCROLL →</p></header><div className="event-track">{events.map((e,i)=><article className={`event-card ${e.hue}`} key={e.id}><div className="event-image"><span>EDC<br/>0{i+1}</span><i/></div><small>{e.date} · {e.category}</small><h3>{e.title}</h3><p>{e.copy}</p><a href="#contact">VIEW EVENT <ArrowUpRight size={15}/></a></article>)}</div></section>
  <section className="featured"><span>06 — FEATURED EVENT</span><div className="summit-globe"/><article><p>EDC SUMMIT / 2026</p><h2>THE ROOM<br/>WHERE <em>NEXT</em><br/>HAPPENS.</h2><div><span>14–15 FEB 2026<br/>CHENNAI, INDIA</span><a className="button" href="#contact">EXPLORE SUMMIT <ArrowUpRight size={16}/></a></div></article></section>
  <section className="people section" id="team"><header><span>07 — PEOPLE</span><h2>THE PEOPLE<br/>BEHIND THE<br/><em>MOVEMENT.</em></h2></header><div className="team-grid">{team.map((x,i)=><button className={`person ${x.tone}`} key={x.id} onClick={()=>setPerson(x)}><div><span>EDC / 0{i+1}</span><i/></div><p>{x.dept}</p><h3>{x.name}</h3><small>{x.role}</small><Linkedin size={16}/></button>)}</div></section>
  <section className="archive section" id="archive"><header><span>08 — DIGITAL LIBRARY</span><h2>THE <em>ARCHIVE</em></h2><p>A living record of the experiments, moments, and ideas that have made us.</p></header><div className="filters">{["ALL","2026","2025","2024","EVENTS","PUBLICATIONS"].map(f=><button onClick={()=>setFilter(f)} className={filter===f?"selected":""} key={f}>{f}</button>)}</div><div className="archive-grid">{filtered.map((a,i)=><article key={a.id}><div className={`archive-thumb t${i}`}><span>{a.year}</span></div><small>{a.category} / {a.type}</small><h3>{a.title}</h3><a href="#contact">OPEN <ArrowUpRight size={14}/></a></article>)}</div></section>
  <section className="ledger section"><header><span>09 — RECORDS</span><h2>EDC <em>LEDGER</em></h2></header><div>{ledger.map(x=><article className="reveal" key={x[0]+x[1]}><b>{x[0]}</b><div><h3>{x[1]}</h3><p>{x[2]}</p></div><Plus size={18}/></article>)}</div></section>
  <section className="voices section"><span>10 — TESTIMONIAL</span><h2>“EDC didn&apos;t just give me a place to pitch. It gave me the nerve to build something worth pitching.”</h2><p>ANANYA RAMAN / STUDENT FOUNDER</p><div><i/><i/><i/></div></section>
  <section className="contact" id="contact"><span>11 — START HERE</span><h2>HAVE AN IDEA?<br/><em>BUILD IT</em><br/>WITH US.</h2><div><a className="button" href="mailto:hello@edc.edu">JOIN EDC <ArrowUpRight/></a><a className="text-link" href="mailto:hello@edc.edu">PARTNER WITH US <ArrowUpRight size={16}/></a></div></section>
  <footer><div className="footer-brand">EDC<span>.</span><p>ENTREPRENEUR DEVELOPMENT CELL</p></div><div><a href="#about">ABOUT</a><a href="#initiatives">INITIATIVES</a><a href="#events">EVENTS</a></div><div><a href="#team">TEAM</a><a href="#archive">ARCHIVE</a><a href="#contact">CONTACT</a></div><div><a href="#">INSTAGRAM</a><a href="#">LINKEDIN</a><a href="mailto:hello@edc.edu">EMAIL</a></div><small>© 2026 EDC. ALL RIGHTS RESERVED.<i/></small></footer>
  {person && <div className="modal" role="dialog" aria-modal="true"><button onClick={()=>setPerson(null)} aria-label="Close profile"><X/></button><div className={`modal-photo ${person.tone}`}/><p>{person.dept}</p><h2>{person.name}</h2><h3>{person.role}</h3><a href="#" onClick={e=>e.preventDefault()}>LINKEDIN <ArrowUpRight size={16}/></a></div>}</main>; }
